language: android
android:
  components:
  - android-22
  - android-26
  - build-tools-26.0.2
  - sys-img-armeabi-v7a-android-26
before_install:
 - chmod +x gradlew
install:
 - echo y | sdkmanager 'ndk-bundle'
 - echo y | sdkmanager 'lldb;3.0'
branches:
  only:
  - master
  - FLOW-UI
before_script:
  - android list sdk --extended --no-ui --all
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-22,sys-img-x86_64-android-22
  - echo "n" | android create avd --name myandroid22 -t "android-22" --abi "default/armeabi-v7a"
  - emulator -avd myandroid22 -no-audio -no-window &
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
notifications:
  slack:
    rooms:
      secure: dvcoFOzz0WB6GwRlY3wiuSXSO23GbJNspbaS7VwjfbwlOMlkYSO0I/4eCxNpCLW8n4wA/XzRnYVxwvDkibh1vznnq3VgZO1VyT24sYmHQkole6BNJ68qXCS0iZFN8ik3/OYcxeOiJ1rWKsSei7VbSXvH1aJY0OIgwk88YSFOR1/ZNwPvvZkBUIHiZUwDQR4plJ/A665FtKsITSmZdgfLpekgD6uVfkzg6SYbE/DmwA8FXvNBvBkEXDW3QzAHJYzs+fhSPoDzCppSaSnV+cdgEWF077TcxZw32Xvx80nfbE9uLNFbIBQaXeSXZfhSzcy40JrawIMpL7jYLrlrghwPSeKU6z5LxBTasrcsnDAllTYOjzRgP+REOiT/72oLYshTlv8Sc91/9ERf5ScfHofTPNVcknTZWiXHcSgUuyT0WLtzHL6CuU+y7wwQdo4pNZTD1i6zRvD35Z31RotGUi7s568/hz6YyjVofG+qdjHElA6NbblmGbGXjLShavZebOh17TxcKJbHNlg9/6QR7AG/yMdpC0n+w4dsTTQ1U0FMvv9lwJdfHI3WbUf0PspSDk87QNyjbFWEqP5mEqklz1OPz1oQrR4Hvrz7FAm4jvlI54BgUiRiEUrvuPrWLFtwewEADAKjEzfBR1Nj+rabcHHP+X06lLX6343SWw5RKWrkXnQ=
